<a href="https://colab.research.google.com/github/Pritishcoder07/AIML-ALGROITHM/blob/main/DAY%205%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**DAY 1**

In [1]:
import pandas as pd

#
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [2]:
df["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [3]:
df.shape

(891, 15)

In [4]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [6]:
df[["age","fare"]]

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [7]:
df.iloc[59]

survived                 0
pclass                   3
sex                   male
age                   11.0
sibsp                    5
parch                    2
fare                  46.9
embarked                 S
class                Third
who                  child
adult_male           False
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 59, dtype: object

In [8]:
df["survived"].sum()

np.int64(342)

In [9]:
df["survived"].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

**PractiseSet**

Tasks:
 1.Total rows aur columns print karo

---

Sirf age, sex,

---


fare columns dikhayo

---


First 10 rows print karo

---


Last 5 rows print karo

---


Sirf male passengers ka data nikalo

In [10]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)

In [11]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [13]:
df.shape

(891, 15)

In [14]:
df[["age","sex"]]

      age     sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
886  27.0    male
887  19.0  female
888   NaN  female
889  26.0    male
890  32.0    male

[891 rows x 2 columns]

In [15]:
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [16]:
df.tail(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [17]:

df[df["sex"] == "male"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [18]:
df[df["sex"] == "male"].shape

(577, 15)

Tasks:
Age > 25 wale passengers dikhayo

---


Female AND survived = 1 wale log

---


Fare > 50 wale passengers

---


Kitne log age > 60 hain? (count nikalna)

---


Kitne male survive hue?

In [19]:
df[df["age"]>25]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [20]:
df[(df["sex"] == "female") & (df["survived"] == 1)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [21]:
df[df["fare"]>50]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

In [22]:
df[df["age"]> 60].count()

survived       22
pclass         22
sex            22
age            22
sibsp          22
parch          22
fare           22
embarked       21
class          22
who            22
adult_male     22
deck           11
embark_town    21
alive          22
alone          22
dtype: int64

In [23]:
df[(df["sex"]=="male")&(df["survived"])]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

Day 2

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]

In [25]:
arr * 2
arr + 10
arr.mean()
arr.max()
arr.min()

np.int64(1)

In [26]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]

In [27]:
arr2.shape

(2, 3)

In [28]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [29]:
df["age_plus_10"] = df["age"] + 10

In [30]:
df["age_plus_10"]

0      32.0
1      48.0
2      36.0
3      45.0
4      45.0
       ...
886    37.0
887    29.0
888     NaN
889    36.0
890    42.0
Name: age_plus_10, Length: 891, dtype: float64

In [31]:
df["fare_double"] = df["fare"]*2
df["fare_double"]

0       14.5000
1      142.5666
2       15.8500
3      106.2000
4       16.1000
         ...
886     26.0000
887     60.0000
888     46.9000
889     60.0000
890     15.5000
Name: fare_double, Length: 891, dtype: float64

In [32]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
age_plus_10    177
fare_double      0
dtype: int64

In [33]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["age"]

/tmp/ipykernel_20398/1576137650.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [34]:
df.sort_values(by="age",ascending=False)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_plus_10,fare_double
630,1,1,male,80.00,0,0,30.0000,S,First,man,True,A,Southampton,yes,True,90.00,60.0000
851,0,3,male,74.00,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True,84.00,15.5500
96,0,1,male,71.00,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True,81.00,69.3084
493,0,1,male,71.00,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True,81.00,99.0084
116,0,3,male,70.50,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,80.50,15.5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False,10.83,37.5000
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False,10.75,38.5166
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False,10.75,38.5166
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False,10.67,29.0000
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False,10.42,17.0334

In [35]:
df.groupby("sex")["survived"].sum()

sex
female    233
male      109
Name: survived, dtype: int64

In [36]:
df["sex"].unique()

array(['male', 'female'], dtype=object)

In [37]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

Practise

In [38]:
arr3 = np.array([1,5,9,7,6])

In [39]:
df = arr3

In [40]:
df.mean()

np.float64(5.6)

In [41]:
arr4 = np.array([[1,5,9,7,3],[9,6,4,7,8]])

In [42]:
arr4

array([[1, 5, 9, 7, 3],
       [9, 6, 4, 7, 8]])

In [43]:
df = arr4

In [44]:
df.shape

(2, 5)

In [45]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [46]:
df["fare_100"]=df["fare"]+100
df["fare_100"]

0      107.2500
1      171.2833
2      107.9250
3      153.1000
4      108.0500
         ...
886    113.0000
887    130.0000
888    123.4500
889    130.0000
890    107.7500
Name: fare_100, Length: 891, dtype: float64

In [47]:
df["age_is_18"]= df["age"]<18
df["age_is_18"]

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: age_is_18, Length: 891, dtype: bool

In [48]:
df["age"].isnull().sum()

np.int64(177)

In [49]:
df["age"].fillna("Notmention",inplace=True)

/tmp/ipykernel_20398/1205805147.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna("Notmention",inplace=True)
/tmp/ipykernel_20398/1205805147.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Notmention' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df["age"].fillna("Notmention",inplace=True)

In [50]:
df["age"]

0            22.0
1            38.0
2            26.0
3            35.0
4            35.0
          ...
886          27.0
887          19.0
888    Notmention
889          26.0
890          32.0
Name: age, Length: 891, dtype: object

In [51]:
df.groupby("pclass")["survived"].sum()

pclass
1    136
2     87
3    119
Name: survived, dtype: int64

**EXTRA PRACTICE SET**

In [52]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [53]:
df["sex"].unique()

array(['male', 'female'], dtype=object)

In [54]:
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [55]:
df[["age","survived"]]

      age  survived
0    22.0         0
1    38.0         1
2    26.0         1
3    35.0         1
4    35.0         0
..    ...       ...
886  27.0         0
887  19.0         1
888   NaN         0
889  26.0         1
890  32.0         0

[891 rows x 2 columns]

In [56]:
df["fare"].head(1)

0    7.25
Name: fare, dtype: float64

In [57]:
df["fare"].isnull().sum()

np.int64(0)

In [58]:
df[(df["age"]<18)&(df["survived"]==1)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.00,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
22,1,3,female,15.00,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
39,1,3,female,14.00,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
43,1,2,female,3.00,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,1,3,female,15.00,1,0,14.4542,C,Third,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
853,1,1,female,16.00,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
875,1,3,female,15.00,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True

In [59]:
df[(df["sex"]=="male")&(df["fare"]>100)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
118,0,1,male,24.00,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
332,0,1,male,38.00,0,1,153.4625,S,First,man,True,C,Southampton,no,False
373,0,1,male,22.00,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
377,0,1,male,27.00,0,2,211.5000,C,First,man,True,C,Cherbourg,no,False
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
438,0,1,male,64.00,1,4,263.0000,S,First,man,True,C,Southampton,no,False
505,0,1,male,18.00,1,0,108.9000,C,First,man,True,C,Cherbourg,no,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
544,0,1,male,50.00,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True
659,0,1,male,58.00,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
660,1,1,male,50.00,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
679,1,1,male,36.00,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
698,0,1,male,49.00,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
737,1,1,male,35.00,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False

In [60]:
df[(df["sex"]=="female")&(df["age"]>30)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
865,1,2,female,42.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False

In [61]:
df[df["pclass"]==3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [62]:
df[df["fare"]>200]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
118,0,1,male,24.0,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
299,1,1,female,50.0,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
311,1,1,female,18.0,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
341,1,1,female,24.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
377,0,1,male,27.0,0,2,211.5000,C,First,man,True,C,Cherbourg,no,False
380,1,1,female,42.0,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
689,1,1,female,15.0,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
700,1,1,female,18.0,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
716,1,1,female,38.0,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
730,1,1,female,29.0,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
742,1,1,female,21.0,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
779,1,1,female,43.0,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False

**DAY 3**

In [63]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [64]:
# sirf important columns use karenge
df = df[["survived", "pclass", "sex", "age", "fare"]]

# missing values fill
df["age"].fillna(df["age"].mean(), inplace=True)

/tmp/ipykernel_20398/2739445152.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)

In [65]:
df["age"].isnull().sum()

np.int64(0)

In [66]:
df["sex"] = df["sex"].map({"male": 0, "female": 1})

In [67]:
X = df[["pclass", "sex", "age", "fare"]]  # input
y = df["survived"]                        # output

In [68]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [69]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [70]:
y_pred = model.predict(X_test)

In [71]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.7932960893854749

In [72]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[93, 18],
       [19, 49]])

In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [74]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [75]:
y_pred = model.predict(X_test)

In [76]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.7835820895522388

In [77]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

In [78]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [79]:
y_pred = model.predict(X_test)

In [80]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.8067226890756303

In [81]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [82]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [83]:
y_pred = model.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.8004484304932735

In [85]:
X = df[["sex", "pclass"]]
Y = df["survived"]

In [86]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train,Y_test = train_test_split(X, Y, test_size=0.2)

In [87]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [88]:
Y_pred = model.predict(X_test)

In [89]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)

0.770949720670391

**Day 4**

In [90]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)

df = df[["survived", "pclass", "sex", "age", "fare"]]
df["age"].fillna(df["age"].mean(), inplace=True)
df["sex"] = df["sex"].map({"male": 0, "female": 1})

/tmp/ipykernel_20398/2314903103.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)

In [91]:
df.head()

   survived  pclass  sex   age     fare
0         0       3    0  22.0   7.2500
1         1       1    1  38.0  71.2833
2         1       3    1  26.0   7.9250
3         1       1    1  35.0  53.1000
4         0       3    0  35.0   8.0500

In [92]:
X = df[["pclass", "sex", "age", "fare"]]
y = df["survived"]

In [93]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [94]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [95]:
DecisionTreeClassifier()

DecisionTreeClassifier()

In [96]:
model = DecisionTreeClassifier(max_depth=3)
model.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=3)

In [97]:
y_pred = model.predict(X_test)

In [98]:
from sklearn.metrics import accuracy_score

accuracy_score(Y_test, Y_pred)

0.5195530726256983

**DAY 5**

In [99]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)

df = df[["survived", "pclass", "sex", "age", "fare"]]
df["age"].fillna(df["age"].mean(), inplace=True)
df["sex"] = df["sex"].map({"male": 0, "female": 1})

/tmp/ipykernel_20398/2314903103.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)

In [100]:
X = df[["pclass", "sex", "age", "fare"]]
y = df["survived"]

In [101]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

In [102]:
model = LogisticRegression(C=0.01)
model.fit(X_train,Y_train)

LogisticRegression(C=0.01)

In [103]:
Y_pred = model.predict(X_test)

In [104]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.7318435754189944

In [105]:
model = LogisticRegression(C=0.1)
model.fit(X_train, Y_train)

LogisticRegression(C=0.1)

In [106]:
Y_pred = model.predict(X_test)

In [107]:
from sklearn.metrics import accuracy_score

accuracy_score(Y_test, Y_pred)

0.7932960893854749

In [108]:
model = LogisticRegression(C=1)
model.fit(X_train,Y_train)

LogisticRegression(C=1)

In [109]:
Y_pred =model.predict(X_test)

In [110]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.7988826815642458

In [111]:
model = LogisticRegression(C=10)
model.fit(X_train, Y_train)

LogisticRegression(C=10)

In [112]:
Y_pred = model.predict(X_test)

In [113]:
from sklearn.metrics import accuracy_score

accuracy_score(Y_test, Y_pred)

0.7988826815642458

Logistic Regression

0.001 - 0.7318435754189944

---
0.1 - 0.7932960893854749

---

1 - 0.7988826815642458


---

10 - 0.7988826815642458

In [114]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=2)
model.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=2)

In [115]:
Y_pred = model.predict(X_test)

In [116]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.7653631284916201

In [117]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=3)
model.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=3)

In [118]:
Y_pred =model.predict(X_test)

In [119]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.7988826815642458

In [120]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth= 5)
model.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=5)

In [121]:
Y_pred = model.predict(X_test)

In [122]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.8044692737430168

In [123]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth= 10)
model.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=10)

In [124]:
Y_pred = model.predict(X_test)

In [125]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.7988826815642458

*DecisionTreeClassifier*

2 - 0.7653631284916201

---
3 - 0.7988826815642458


---

5 - 0.8044692737430168



---
10 - 0.7821229050279329

In [126]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=50)
model.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=50)

In [127]:
Y_pred= model.predict(X_test)

In [128]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.8156424581005587

In [129]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train,Y_train)

RandomForestClassifier()

In [130]:
Y_pred = model.predict(X_test)

In [131]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.7877094972067039

In [132]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=200)
model.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=200)

In [133]:
Y_pred = model.predict(X_test)

In [134]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.7877094972067039

*Random Forest*

50 - 0.7877094972067039


---

100 - 0.8044692737430168

---

200 - 0.7877094972067039

In [135]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)

df["age"].fillna(df["age"].mean(), inplace=True)
df["sex"] = df["sex"].map({"male": 0, "female": 1})

/tmp/ipykernel_20398/1003761471.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)

In [136]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [137]:
df["family_size"] = df["sibsp"] + df["parch"]

In [138]:
df["is_alone"] = (df["family_size"] == 0).astype(int)

In [139]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,is_alone
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,0
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,0
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,1
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,0
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,1

In [140]:
df["age_group"] = pd.cut(df["age"], bins=[0,18,40,60,100], labels=[0,1,2,3])

In [141]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,is_alone,age_group
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,0,1
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,0,1
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,1,1
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,0,1
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,1,1

In [142]:
df["fare_group"] = pd.cut(df["fare"], bins=3, labels=[0,1,2])

In [143]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,is_alone,age_group,fare_group
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,0,1,0
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,0,1,0
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,1,1,0
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,0,1,0
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,1,1,0

In [144]:
df["age_group"] = df["age_group"].astype(int)
df["fare_group"] = df["fare_group"].astype(int)

In [145]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,is_alone,age_group,fare_group
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,0,1,0
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,0,1,0
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,1,1,0
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,0,1,0
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,1,1,0

In [146]:
X = df[[
    "pclass", "sex", "age", "fare",
    "family_size", "is_alone",
    "age_group", "fare_group"
]]

y = df["survived"]

In [147]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy_score(y_test, y_pred)

0.8212290502793296

without - 0.7877094972067039


---

with - 0.8212290502793296

In [148]:
importance = model.feature_importances_

import pandas as pd

pd.DataFrame({
    "Feature": X.columns,
    "Importance": importance
}).sort_values(by="Importance", ascending=False)

       Feature  Importance
3         fare    0.291752
1          sex    0.273737
2          age    0.237133
0       pclass    0.080047
4  family_size    0.064919
6    age_group    0.031006
5     is_alone    0.013673
7   fare_group    0.007733

In [149]:
X = df[["pclass", "sex", "age", "fare"]]
Y = df[["survived"]]

In [150]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy_score(y_test, y_pred)

0.7877094972067039

In [151]:
X = df[["pclass", "sex", "family_size", "is_alone"]]
Y = df[["survived"]]

In [152]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy_score(y_test, y_pred)

0.8044692737430168

In [153]:
X = df[["pclass", "sex", "family_size"]]
Y = df[["survived"]]

In [154]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy_score(y_test, y_pred)

0.8044692737430168

Cross validation

hyperparamete

IS LEFT

In [155]:
# Step 1: split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Step 2: CV on training data
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_train, y_train, cv=5)

# Step 3: train final model
model.fit(X_train, y_train)

# Step 4: final test
model.score(X_test, y_test)

0.8156424581005587

In [156]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.68      0.67      0.67       115
           1       0.42      0.42      0.42        64

    accuracy                           0.58       179
   macro avg       0.55      0.55      0.55       179
weighted avg       0.58      0.58      0.58       179

In [157]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(class_weight="balanced")

In [158]:
model = RandomForestClassifier(n_estimators=100, class_weight="balanced")

In [159]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.68      0.67      0.67       115
           1       0.42      0.42      0.42        64

    accuracy                           0.58       179
   macro avg       0.55      0.55      0.55       179
weighted avg       0.58      0.58      0.58       179

In [160]:
print("hello")

hello